package rules

// Comprehensive policies for Gaming, Streaming, Developer Tools, and Security Filters
var (
	// --- GAMING POLICIES ---

	// Riot Games: League of Legends, Valorant, Vanguard, Riot Client, Chat/Friends, Store/Banners, Wild Rift, TFT, LoR
	PresetRiot = []string{
		"riotgames.com",
		"*.riotgames.com",
		"leagueoflegends.com",
		"*.leagueoflegends.com",
		"playvalorant.com",
		"*.playvalorant.com",
		"pvp.net",
		"*.pvp.net",
		"riotcdn.net",
		"*.riotcdn.net",
		"rdatasvc.net",
		"*.rdatasvc.net",
		"wr.pvp.net",
		"*.wr.pvp.net",
		"rgpub.io",
		"*.rgpub.io",
		"riotstatus.com",
		"*.riotstatus.com",
		"riot-games.edgesuite.net",
		"*.riot-games.edgesuite.net",
		"launchdarkly.com",
		"*.launchdarkly.com",
		"app.launchdarkly.com",
		"clientstream.launchdarkly.com",
		"events.launchdarkly.com",
		"sentry.io",
		"*.sentry.io",
		"datadoghq.com",
		"*.datadoghq.com",
		"riotgames.zendesk.com",
		"bnet.mobi",
		"*.bnet.mobi",
		"playruneterra.com",
		"*.playruneterra.com",
		"teamfighttactics.leagueoflegends.com",
		"wildrift.leagueoflegends.com",
		"riotgames.co.kr",
		"*.riotgames.co.kr",
		"riotgames.jp",
		"*.riotgames.jp",
		"riotgames.com.tr",
		"*.riotgames.com.tr",
		"riotgames.eu",
		"*.riotgames.eu",
		"val.services.riotgames.com",
		"playerplatform.riotgames.com",
		"auth.riotgames.com",
		"entitlements.auth.riotgames.com",
		"edge.riotgames.com",
		"cloud.riotgames.com",
		"rec.riotgames.com",
		"anticheat.riotgames.com",
		"vanguard.riotgames.com",
		"cdr.riotgames.com",
		"content.developer.riotgames.com",
		"valorantesports.com",
		"*.valorantesports.com",
		"lolesports.com",
		"*.lolesports.com",
		"riot-client.riotgames.com",
		"vivox.com",
		"*.vivox.com",
		"bop.vivox.com",
		"*.bop.vivox.com",
		"v5.vivox.com",
		"*.v5.vivox.com",
	}

	// Epic Games: Store, Unreal Engine, Fortnite, Fall Guys, Rocket League, Easy Anti-Cheat
	PresetEpic = []string{
		"epicgames.com",
		"*.epicgames.com",
		"epicgames.dev",
		"*.epicgames.dev",
		"unrealengine.com",
		"*.unrealengine.com",
		"unrealengine.dev",
		"*.unrealengine.dev",
		"easyanticheat.net",
		"*.easyanticheat.net",
		"eac-cdn.com",
		"*.eac-cdn.com",
		"eac.easyanticheat.net",
		"fortnite.com",
		"*.fortnite.com",
		"fallguys.com",
		"*.fallguys.com",
		"rocketleague.com",
		"*.rocketleague.com",
		"psyonix.com",
		"*.psyonix.com",
		"epicgames.net",
		"*.epicgames.net",
		"epicgames-download.akamaized.net",
		"*.epicgames-download.akamaized.net",
		"epicgames-download1.akamaized.net",
		"*.epicgames-download1.akamaized.net",
		"ol.epicgames.com",
		"account.epicgames.com",
		"tracking.epicgames.com",
		"epicgames.statuspage.io",
		"live.epicgames.com",
	}

	// Steam & Valve: Store, Community, Dota 2, CS2, Deadlock, Steam CDN, VAC
	PresetSteam = []string{
		"steampowered.com",
		"*.steampowered.com",
		"steamcommunity.com",
		"*.steamcommunity.com",
		"steamstatic.com",
		"*.steamstatic.com",
		"steamcontent.com",
		"*.steamcontent.com",
		"steamserver.net",
		"*.steamserver.net",
		"valvesoftware.com",
		"*.valvesoftware.com",
		"steamgames.com",
		"*.steamgames.com",
		"steam-chat.com",
		"*.steam-chat.com",
		"counter-strike.net",
		"*.counter-strike.net",
		"dota2.com",
		"*.dota2.com",
		"underlords.com",
		"*.underlords.com",
		"playartifact.com",
		"*.playartifact.com",
		"steamdeck.com",
		"*.steamdeck.com",
		"steamstat.us",
		"*.steamstat.us",
		"steamcommunity-a.akamaihd.net",
		"*.steamcommunity-a.akamaihd.net",
		"steamusercontent-a.akamaihd.net",
		"*.steamusercontent-a.akamaihd.net",
		"faceit.com",
		"*.faceit.com",
		"faceitcdn.net",
		"*.faceitcdn.net",
	}

	// Electronic Arts: EA App, Origin, Apex Legends, Battlefield, EA FC / FIFA, Respawn, Frostbite
	PresetEA = []string{
		"ea.com",
		"*.ea.com",
		"origin.com",
		"*.origin.com",
		"electronicarts.com",
		"*.electronicarts.com",
		"eaassets-a.akamaihd.net",
		"*.eaassets-a.akamaihd.net",
		"respawn.com",
		"*.respawn.com",
		"apexlegends.com",
		"*.apexlegends.com",
		"eafc.com",
		"*.eafc.com",
		"battlefield.com",
		"*.battlefield.com",
		"tiberiumalliances.com",
		"*.tiberiumalliances.com",
		"ea.com.cn",
		"*.ea.com.cn",
		"eacdn.com",
		"*.eacdn.com",
		"origin-a.akamaihd.net",
		"*.origin-a.akamaihd.net",
		"sims.com",
		"*.sims.com",
		"help.ea.com",
		"answers.ea.com",
	}

	// Blizzard: Battle.net, Overwatch 2, WoW, Diablo IV, Hearthstone, StarCraft
	PresetBlizzard = []string{
		"battle.net",
		"*.battle.net",
		"blizzard.com",
		"*.blizzard.com",
		"blzstatic.com",
		"*.blzstatic.com",
		"battlenet.com",
		"*.battlenet.com",
		"overwatch2.com",
		"*.overwatch2.com",
		"playoverwatch.com",
		"*.playoverwatch.com",
		"diablo.com",
		"*.diablo.com",
		"diablo4.com",
		"*.diablo4.com",
		"worldofwarcraft.com",
		"*.worldofwarcraft.com",
		"hearthstone.com",
		"*.hearthstone.com",
		"blizzard.cn",
		"*.blizzard.cn",
		"battlenet.com.cn",
		"*.battlenet.com.cn",
		"bnetcmsus-a.akamaihd.net",
		"*.bnetcmsus-a.akamaihd.net",
	}

	// Ubisoft: Ubisoft Connect, Rainbow Six Siege, Assassin's Creed, Far Cry, The Division, XDefiant, BattlEye
	PresetUbisoft = []string{
		"ubisoft.com",
		"*.ubisoft.com",
		"ubi.com",
		"*.ubi.com",
		"ubisoftconnect.com",
		"*.ubisoftconnect.com",
		"uplay.com",
		"*.uplay.com",
		"rainbow6.com",
		"*.rainbow6.com",
		"assassinscreed.com",
		"*.assassinscreed.com",
		"xdefiant.com",
		"*.xdefiant.com",
		"trackmania.com",
		"*.trackmania.com",
		"thedivisiongame.com",
		"*.thedivisiongame.com",
		"ubisoft.ca",
		"*.ubisoft.ca",
		"static-asset-delivery.cloud.ubi.com",
		"*.static-asset-delivery.cloud.ubi.com",
		"battleye.com",
		"*.battleye.com",
	}

	// Rockstar Games: GTA V / GTA Online, GTA VI, Red Dead Redemption 2, Social Club, Rockstar Launcher
	PresetRockstar = []string{
		"rockstargames.com",
		"*.rockstargames.com",
		"rockstarnorth.com",
		"*.rockstarnorth.com",
		"rsg.sc",
		"*.rsg.sc",
		"socialclub.rockstargames.com",
		"*.socialclub.rockstargames.com",
		"gtaonline.com",
		"*.gtaonline.com",
		"reddeadonline.com",
		"*.reddeadonline.com",
		"rockstargames.statuspage.io",
		"prod.ros.rockstargames.com",
	}

	// Xbox & Microsoft Gaming: Xbox Live, Game Pass, Minecraft, PlayFab, Bethesda, Sea of Thieves, Halo, Forza
	PresetXbox = []string{
		"xbox.com",
		"*.xbox.com",
		"xboxlive.com",
		"*.xboxlive.com",
		"playfabapi.com",
		"*.playfabapi.com",
		"minecraft.net",
		"*.minecraft.net",
		"minecraftservices.com",
		"*.minecraftservices.com",
		"mojang.com",
		"*.mojang.com",
		"bethesda.net",
		"*.bethesda.net",
		"bethsoft.com",
		"*.bethsoft.com",
		"xboxab.com",
		"*.xboxab.com",
		"xboxservices.com",
		"*.xboxservices.com",
		"xboxgamestudios.com",
		"*.xboxgamestudios.com",
		"gamepass.com",
		"*.gamepass.com",
		"forzamotorsport.net",
		"*.forzamotorsport.net",
		"seaofthieves.com",
		"*.seaofthieves.com",
		"halowaypoint.com",
		"*.halowaypoint.com",
	}

	// PlayStation: PSN, PlayStation Store, Sony Network, PS5, SIE
	PresetPlayStation = []string{
		"playstation.com",
		"*.playstation.com",
		"playstation.net",
		"*.playstation.net",
		"playstationnetwork.com",
		"*.playstationnetwork.com",
		"sonyentertainmentnetwork.com",
		"*.sonyentertainmentnetwork.com",
		"playstation.com.cn",
		"*.playstation.com.cn",
		"sie.com",
		"*.sie.com",
		"psn.dl.playstation.net",
		"*.psn.dl.playstation.net",
		"account.np.ac.playstation.net",
		"auth.np.ac.playstation.net",
	}

	// Roblox: Game Client, Studio, RBXCDN, Physics, Assets
	PresetRoblox = []string{
		"roblox.com",
		"*.roblox.com",
		"rbxcdn.com",
		"*.rbxcdn.com",
		"roblox.cn",
		"*.roblox.cn",
		"robloxlabs.com",
		"*.robloxlabs.com",
		"rbx.com",
		"*.rbx.com",
		"setup.rbxcdn.com",
		"versioncompatibility.api.roblox.com",
	}

	// PUBG: Mobile, PC, Krafton, Level Infinite, ProximaBeta, Lightspeed, Midasbuy, Tencent Cloud Engine
	PresetPUBG = []string{
		"pubg.com",
		"*.pubg.com",
		"pubgmobile.com",
		"*.pubgmobile.com",
		"krafton.com",
		"*.krafton.com",
		"proximabeta.com",
		"*.proximabeta.com",
		"levelinfinite.com",
		"*.levelinfinite.com",
		"igamebuy.com",
		"*.igamebuy.com",
		"midasbuy.com",
		"*.midasbuy.com",
		"intlgame.com",
		"*.intlgame.com",
		"lightspeedquantum.com",
		"*.lightspeedquantum.com",
		"pubgmobile.in",
		"*.pubgmobile.in",
		"newstate.pubg.com",
		"*.newstate.pubg.com",
		"pubgtool.com",
		"*.pubgtool.com",
		"pubgmobile.sg",
		"*.pubgmobile.sg",
		"cloudpvp.com",
		"*.cloudpvp.com",
		"gcloudcs.com",
		"*.gcloudcs.com",
		"gcloud.qq.com",
		"*.gcloud.qq.com",
		"igamecj.com",
		"*.igamecj.com",
		"tpns.tencent.com",
		"*.tpns.tencent.com",
		"wetest.qq.com",
		"*.wetest.qq.com",
		"timi.qq.com",
		"*.timi.qq.com",
	}

	// Call of Duty: Warzone, Modern Warfare, Black Ops, CoD Mobile, Activision, Demonware Matchmaking
	PresetCallOfDuty = []string{
		"callofduty.com",
		"*.callofduty.com",
		"activision.com",
		"*.activision.com",
		"demonware.net",
		"*.demonware.net",
		"atvi.com",
		"*.atvi.com",
		"codm.garena.com",
		"*.codm.garena.com",
		"callofduty.garena.com",
		"*.callofduty.garena.com",
		"ravensoftware.com",
		"*.ravensoftware.com",
		"treyarch.com",
		"*.treyarch.com",
		"infinityward.com",
		"*.infinityward.com",
		"sledgehammergames.com",
		"*.sledgehammergames.com",
		"uno.demonware.net",
		"*.uno.demonware.net",
		"auth.demonware.net",
		"*.auth.demonware.net",
		"codwarzone.com",
		"*.codwarzone.com",
		"callofdutywarzone.com",
		"*.callofdutywarzone.com",
	}

	// Supercell: Brawl Stars, Clash of Clans, Clash Royale, Squad Busters, Hay Day, Boom Beach, Supercell ID
	PresetSupercell = []string{
		"supercell.com",
		"*.supercell.com",
		"supercellid.com",
		"*.supercellid.com",
		"clashofclans.com",
		"*.clashofclans.com",
		"clashroyale.com",
		"*.clashroyale.com",
		"brawlstars.com",
		"*.brawlstars.com",
		"brawlstarsgame.com",
		"*.brawlstarsgame.com",
		"squadbustersgame.com",
		"*.squadbustersgame.com",
		"squadbusters.game",
		"*.squadbusters.game",
		"haydaygame.com",
		"*.haydaygame.com",
		"boombeach.com",
		"*.boombeach.com",
		"supercell.net",
		"*.supercell.net",
		"supercell-cdn.net",
		"*.supercell-cdn.net",
		"id.supercell.com",
	}

	// --- STREAMING & MEDIA POLICIES ---

	// Discord: Gateway, Voice (RTC), Updates, Media, CDN, API
	PresetDiscord = []string{
		"discord.com",
		"*.discord.com",
		"discord.gg",
		"*.discord.gg",
		"discordapp.com",
		"*.discordapp.com",
		"discordapp.net",
		"*.discordapp.net",
		"discord.media",
		"*.discord.media",
		"discordcdn.com",
		"*.discordcdn.com",
		"discord.co",
		"*.discord.co",
		"discord.gift",
		"*.discord.gift",
		"discord.new",
		"*.discord.new",
		"dis.gd",
		"*.dis.gd",
		"discordstatus.com",
		"*.discordstatus.com",
		"discord-activities.com",
		"*.discord-activities.com",
		"discordapp.io",
		"*.discordapp.io",
		"latency.discord.media",
		"router.discordapp.net",
		"updates.discord.com",
		"*.updates.discord.com",
		"dl.discordapp.net",
		"*.dl.discordapp.net",
		"dl-media.discordapp.net",
		"discord-attachments-uploads-prd.storage.googleapis.com",
	}

	// Twitch: Live Streams & Chat
	PresetTwitch = []string{
		"twitch.tv",
		"*.twitch.tv",
		"ttvnw.net",
		"*.ttvnw.net",
		"jtvnw.net",
		"*.jtvnw.net",
		"twitchcdn.net",
		"*.twitchcdn.net",
	}

	// Kick: Streaming Platform
	PresetKick = []string{
		"kick.com",
		"*.kick.com",
		"kickstream.com",
		"*.kickstream.com",
	}

	// Spotify: Music streaming anti-sanction
	PresetSpotify = []string{
		"spotify.com",
		"*.spotify.com",
		"scdn.co",
		"*.scdn.co",
		"spotifycdn.com",
		"*.spotifycdn.com",
		"spoti.fi",
		"*.spoti.fi",
		"audio-ak-spotify-com.akamaized.net",
		"*.audio-ak-spotify-com.akamaized.net",
	}

	// --- DEVELOPER & AI POLICIES ---

	PresetDev403 = []string{
		"docker.com",
		"*.docker.com",
		"docker.io",
		"*.docker.io",
		"registry-1.docker.io",
		"auth.docker.io",
		"gradle.org",
		"*.gradle.org",
		"android.com",
		"*.android.com",
		"developer.android.com",
		"source.android.com",
		"openai.com",
		"*.openai.com",
		"chatgpt.com",
		"*.chatgpt.com",
		"oaistatic.com",
		"*.oaistatic.com",
		"oaiusercontent.com",
		"*.oaiusercontent.com",
		"anthropic.com",
		"*.anthropic.com",
		"claude.ai",
		"*.claude.ai",
		"npmjs.org",
		"*.npmjs.org",
		"npmjs.com",
		"*.npmjs.com",
		"registry.npmjs.org",
		"maven.org",
		"*.maven.org",
		"mongodb.com",
		"*.mongodb.com",
		"mongodb.org",
		"*.mongodb.org",
		"oracle.com",
		"*.oracle.com",
		"sentry.io",
		"*.sentry.io",
		"elastic.co",
		"*.elastic.co",
		"huggingface.co",
		"*.huggingface.co",
		"supabase.com",
		"*.supabase.com",
		"vercel.com",
		"*.vercel.com",
		"jetbrains.com",
		"*.jetbrains.com",
		"pypi.org",
		"*.pypi.org",
	}

	// --- SECURITY & PRIVACY SINKHOLE POLICIES ---

	// AdBlock & Tracker Sinkhole (Pi-hole / AdGuard style)
	PresetAdBlock = []string{
		"doubleclick.net",
		"*.doubleclick.net",
		"google-analytics.com",
		"*.google-analytics.com",
		"googletagservices.com",
		"*.googletagservices.com",
		"adservice.google.com",
		"*.adservice.google.com",
		"app-measurement.com",
		"*.app-measurement.com",
		"analytics.yahoo.com",
		"*.analytics.yahoo.com",
		"ads.tiktok.com",
		"*.ads.tiktok.com",
		"analytics.tiktok.com",
		"*.analytics.tiktok.com",
		"adservice.sigmob.cn",
		"*.adservice.sigmob.cn",
		"adcolony.com",
		"*.adcolony.com",
		"unityads.unity3d.com",
		"*.unityads.unity3d.com",
		"vungle.com",
		"*.vungle.com",
		"ironsrc.mobi",
		"*.ironsrc.mobi",
	}

	// Family Friendly & Adult Content Protection
	PresetFamilySafe = []string{
		"pornhub.com",
		"*.pornhub.com",
		"xvideos.com",
		"*.xvideos.com",
		"xnxx.com",
		"*.xnxx.com",
		"xhamster.com",
		"*.xhamster.com",
		"redtube.com",
		"*.redtube.com",
		"youporn.com",
		"*.youporn.com",
		"chaturbate.com",
		"*.chaturbate.com",
		"onlyfans.com",
		"*.onlyfans.com",
	}
)
