package matcher

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// TestEmbeddedPresetsMatchGolden pins the JSON-backed catalog to exactly what
// the hard-coded presets.go returned before the v2.3.0 migration: same preset
// names, same domains, same order. The snapshot was generated by
// tools/genpresets from the pre-migration source, so a loader that drops,
// reorders or mangles an entry fails here rather than in a subscriber's game.
func TestEmbeddedPresetsMatchGolden(t *testing.T) {
	raw, err := os.ReadFile("testdata/presets_golden.json")
	if err != nil {
		t.Fatalf("read golden snapshot: %v", err)
	}
	var golden []struct {
		Name    string   `json:"name"`
		Domains []string `json:"domains"`
	}
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("parse golden snapshot: %v", err)
	}

	got := GetAllPresets()
	if len(got) != len(golden) {
		t.Fatalf("preset count = %d, want %d", len(got), len(golden))
	}
	for _, g := range golden {
		domains, ok := got[g.Name]
		if !ok {
			t.Fatalf("preset %q missing from GetAllPresets()", g.Name)
		}
		if !reflect.DeepEqual(domains, g.Domains) {
			t.Fatalf("preset %q domains differ from golden snapshot", g.Name)
		}
	}
}
