/** Purge configuration for the committed Tailwind build.
 *
 *  This file exists on the development machine only. The OUTPUT
 *  (web/css/tailwind.purged.css) is committed and embedded; no Node runs at
 *  build time on the deployment side. Re-run:
 *
 *      npx tailwindcss@3.4.17 -c tools/tailwind.config.js \
 *          -i tools/tailwind.input.css -o web/css/tailwind.purged.css --minify
 *
 *  content scans every place a class name can appear, including the JS
 *  template literals that build dashboard rows at runtime.
 *  safelist carries the values that are only ever concatenated into class
 *  attributes from variables (badge/dot/tone state classes) — the scanner
 *  sees those only as fragments, so they are listed by hand. The list below
 *  was generated by extracting every class attribute from index.html,
 *  app.js and i18n.js plus the enumerated interpolation values.
 */
module.exports = {
  darkMode: 'class',
  content: {
    files: ['web/index.html', 'web/js/app.js', 'web/js/i18n.js', 'web/js/modules/twofa.js'],
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-body)'],
        mono: ['var(--font-mono)'],
      },
      colors: {
        slate: {
          50: 'rgb(var(--c-slate-50) / <alpha-value>)',
          100: 'rgb(var(--c-slate-100) / <alpha-value>)',
          200: 'rgb(var(--c-slate-200) / <alpha-value>)',
          300: 'rgb(var(--c-slate-300) / <alpha-value>)',
          400: 'rgb(var(--c-slate-400) / <alpha-value>)',
          500: 'rgb(var(--c-slate-500) / <alpha-value>)',
          600: 'rgb(var(--c-slate-600) / <alpha-value>)',
          700: 'rgb(var(--c-slate-700) / <alpha-value>)',
          800: 'rgb(var(--c-slate-800) / <alpha-value>)',
          900: 'rgb(var(--c-slate-900) / <alpha-value>)',
          950: 'rgb(var(--c-slate-950) / <alpha-value>)',
        },
        cyan: {
          200: 'rgb(var(--c-cyan-200) / <alpha-value>)',
          300: 'rgb(var(--c-cyan-300) / <alpha-value>)',
          400: 'rgb(var(--c-cyan-400) / <alpha-value>)',
          500: 'rgb(var(--c-cyan-500) / <alpha-value>)',
          950: 'rgb(var(--c-cyan-950) / <alpha-value>)',
        },
        white: 'rgb(var(--c-white) / <alpha-value>)',
        red: {
          300: 'rgb(var(--c-red-300) / <alpha-value>)',
          400: 'rgb(var(--c-red-400) / <alpha-value>)',
          500: 'rgb(var(--c-red-500) / <alpha-value>)',
          600: 'rgb(var(--c-red-600) / <alpha-value>)',
          700: 'rgb(var(--c-red-700) / <alpha-value>)',
          900: 'rgb(var(--c-red-900) / <alpha-value>)',
          950: 'rgb(var(--c-red-950) / <alpha-value>)',
        },
        emerald: {
          300: 'rgb(var(--c-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--c-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--c-emerald-500) / <alpha-value>)',
        },
        amber: {
          300: 'rgb(var(--c-amber-300) / <alpha-value>)',
          400: 'rgb(var(--c-amber-400) / <alpha-value>)',
          500: 'rgb(var(--c-amber-500) / <alpha-value>)',
        },
        blue: {
          200: 'rgb(var(--c-blue-200) / <alpha-value>)',
          300: 'rgb(var(--c-blue-300) / <alpha-value>)',
          400: 'rgb(var(--c-blue-400) / <alpha-value>)',
          500: 'rgb(var(--c-blue-500) / <alpha-value>)',
          600: 'rgb(var(--c-blue-600) / <alpha-value>)',
        },
        purple: {
          300: 'rgb(var(--c-purple-300) / <alpha-value>)',
          400: 'rgb(var(--c-purple-400) / <alpha-value>)',
          500: 'rgb(var(--c-purple-500) / <alpha-value>)',
          600: 'rgb(var(--c-purple-600) / <alpha-value>)',
          700: 'rgb(var(--c-purple-700) / <alpha-value>)',
        },
        orange: {
          300: 'rgb(var(--c-orange-300) / <alpha-value>)',
          400: 'rgb(var(--c-orange-400) / <alpha-value>)',
          500: 'rgb(var(--c-orange-500) / <alpha-value>)',
          600: 'rgb(var(--c-orange-600) / <alpha-value>)',
        },
        yellow: {
          400: 'rgb(var(--c-yellow-400) / <alpha-value>)',
          500: 'rgb(var(--c-yellow-500) / <alpha-value>)',
        },
        indigo: {
          500: 'rgb(var(--c-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--c-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--c-indigo-700) / <alpha-value>)',
        },
        rose: {
          500: 'rgb(var(--c-rose-500) / <alpha-value>)',
          600: 'rgb(var(--c-rose-600) / <alpha-value>)',
          700: 'rgb(var(--c-rose-700) / <alpha-value>)',
        },
        teal: {
          500: 'rgb(var(--c-teal-500) / <alpha-value>)',
        },
        onfill: '#ffffff',
      },
    },
  },
  safelist: [
    'text-emerald-400', 'text-red-400', 'text-amber-400', 'text-slate-300',
    'remove-proxied', 'remove-blocked', 'remove-token',
    'w-2', 'h-2', 'rounded-full', 'bg-slate-600', 'bg-emerald-400', 'bg-yellow-400', 'bg-red-400',
    'bg-slate-500/10', 'border-slate-600/40', 'bg-emerald-500/10', 'border-emerald-500/30',
    'bg-yellow-500/10', 'border-yellow-500/30', 'bg-red-500/10', 'border-red-500/30',
    'text-slate-400', 'text-slate-500', 'text-amber-400', 'font-bold', 'text-red-400',
    'text-lg', 'sm:text-xl', 'font-extrabold', 'font-mono', 'text-cyan-400',
    'px-2.5', 'py-0.5', 'rounded-full', 'bg-cyan-500/10', 'border-cyan-500/30',
    'flex', 'items-center', 'gap-1.5', 'text-[10px]', 'bg-amber-500/10', 'bg-amber-500/15', 'border-amber-500/30',
    'pulse-dot', 'is-stale',
    'bg-purple-500/20', 'text-purple-300', 'border-purple-500/30', 'text-[9px]',
    'text-emerald-400/80', 'text-[9px]', 'inline-flex', 'gap-1',
    'text-cyan-300', 'text-slate-200', 'font-semibold',
    'text-white', 'text-slate-500', 'ms-1.5', 'w-2.5', 'h-2.5',
    'text-center', 'py-6', 'text-xs', 'mt-1', 'text-slate-500',
    'bg-emerald-400', 'bg-red-400',
  ],
};
